#!/bin/bash
# To add user to the PPTP VPN (No harm to run more than once)

apt -y install pwgen
apt -y install gpw

#Automatic Adding VPN Users
USER_NAME=$(gpw 1 8)
USER_PASSWORD=$(pwgen 12 1)

#echo "Username to be added, e.g. debihard, press <Enter> to quit :"
#read USER_NAME

#echo "Password, use a very strong password for this VPN as it is not very secure :"
#read USER_PASSWORD

if ( [[ ! -z "$USER_NAME" ]] ) && ( [[ ! -z "$USER_PASSWORD" ]] ); then
	echo -e "$USER_NAME \x09 * \x09 $USER_PASSWORD \x09 *" >>  /etc/ppp/chap-secrets
	echo "DebiTor VPN user is added!"
	echo "Save your connect - $USER_NAME : $USER_PASSWORD !"
else
	echo "One of the items is empty!  User not added!"
fi

# end of file
