#!/bin/bash
# To delete PPTP VPN user (No harm to run more than once)


echo "Username to be deleted, e.g. debihard, press <Enter> to quit :"
read USER_NAME

if ( [[ ! -z "$USER_NAME" ]] ) ; then
	sed -i "/$USER_NAME/d" /etc/ppp/chap-secrets
	echo "DebiTorVPN user is deleted!"
else
	echo "One of the items is empty!  User not deleted!"
fi

# end of file
