#!/bin/bash
# To update DebiTor (No harm to run more than once)


echo "DebiTor is updating ...."
sudo apt update
sudo apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes -y dist-upgrade
sudo apt -y autoclean
sudo apt -y --purge autoremove
echo "Update is completed.  If Kernel and/or Kernel modules are updated, please reboot the box."

# end of file
