#!/bin/bash
# To update NightHawk (No harm to run more than once)
# Author  : Samiux
# Date    : JUL 20, 2017
# Version : 0.1
# License : GPLv3 (Open Source Software)

echo "NightHawk is updating ...."
sudo apt update
sudo apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes -y dist-upgrade
sudo apt -y autoclean
sudo apt -y --purge autoremove
echo "Update is completed.  If Kernel and/or Kernel modules are updated, please reboot the box."

# end of file
